### ISSUE TITLE
Clean repo to remove ROM and reduce size

### ISSUE THREAD

**Issue by laqieer** [Klokinator/FE-Repo-Music#1]
```
$ git rev-list --objects --all | grep "$(git verify-pack -v .git/objects/pack/*.idx | sort -k 3 -n | tail -20 | awk '{print$1}')"
b84b71dc013391ac9c9e86f9c4fea911164d77d7 [AA] Direct Play .S Files {7743}/FE8 USA.sappy.gba
b03357e4069191334d2334d8ec387198f5897c65 Music Files/Castlevania 3 - Aquarius (MeatOfJustice).wav
458c0da2251c48d6170417c2b88f4a6597c9ecb8 Music Files/Castlevania Order of Ecclesia - Tower of Dolls (Psyche).wav
31e9ac09686adedbeeaa1f5f2e31a896e621a499 Music Files/Donkey Kong Country 1 - Gang-Plank Galleon (MeatOfJustice).wav
0b9be2a7dc2f8c8d0007275fd706c601868bd219 Music Files/Fatal Fury - Soy Sauce for Geese (MeatOfJustice).wav
51dcf6b64ff450925d26a86491778fcc2faa3887 Music Files/Guilty Gear X - Dizzy's Theme - Awe of She (MeatOfJustice).wav
9f38bec512994355e39626c1981160f5074a18ce Music Files/Guilty Gear X - May's Theme - Blue Water Blue Sky (MeatOfJustice).wav
35fbf3aad0cae4e3233949a885a2d645c8d4a1db Music Files/Guilty Gear X - Millia Rage's Theme - Writhe in Pain (MeatOfJustice).wav
85c5913d56e4e015527388fdccae9e555570d146 Music Files/Guilty Gear X - Testament's Theme - Bloodstained Lineage (MeatOfJustice).wav
64dd7e50de0b66e2a5c4a23de3416bb6707b43c8 Music Files/Kid Icarus - Underworld (DonkinDo).AVI
7395f6f0dd2798d31bed9e6363dca7f5ef219e8a Music Files/Lord of the Rings Volume 1 - Main Theme (Psyche).wav
030b5a39b0b49b630d3ec6bb3ce81bbcb9ebc3a5 Music Files/Mario Tennis - Tournament Round 2 (Psyche).wav
3e15c2f2b02c1f7dee780687ce3ce7da4ac433e1 Music Files/Marvel vs Capcom Clash of the Superheroes - Captain America's Theme (MeatOfJustice).wav
cc6a26c168900459c449507c3e8717efbafd7613 Music Files/Phoenix Wright Ace Attorney - Pursuit (Cornered) (MeatOfJustice).wav
69a5744d9f0012b7be7c942a462d24df76e09f50 Music Files/Pokemon Mystery Dungeon Explorers of Sky - Defend Globe (Psyche).wav
1128457510aad254a75db65c5b6d9537c916c377 Music Files/Shin Megami Tensei 3 Nocturne - Big Map (MeatOfJustice).wav
58fa37823db7f9b62a1a701194ec182d4eb4751d Music Files/Sonic the Hedgehog 3 - Angel Island Zone Act 2 (MeatOfJustice).wav
0018e2f57e83245c14b4e2d28bc9c687a45ea1cc Music Files/Street Fighter 2 - Ryu's Theme (MeatOfJustice).wav
3abf94519065ecad652072035f9d4ebccc3ad824 Music Files/TRS Berwick Saga-Departure(RSflame).mp3
f2c1efd8f3c61ab712f2cd754762d13974a6b6c3 Music Files/The King of Fighters '96 - Stormy Saxophone 2 (Team Yagami) (MeatOfJustice).wav
```
As you can see, this repo holds useless files including:
- GBA rom, which causes legal problem
- deleted preview audios and videos, which increases repo size and makes it hard to clone

Therefore I suggest to clean it.

> I already removed the rom. 

You didn't remove it from version control so it is still in Git.

> And the music preview files are staying... sort of the whole point of including them by splitting the music repo into its own thing.

I never suggest to remove preview files in this issue.

> Also considering you're working off some old build of this repo, you might want to update.

I did fork the repo but for my own purpose, not for pr. I forked from the latest build but altered the history to remove those useless files from control version by myself later so you see `xxx commits ahead` and `xxx commits behind` but it is not from old builds.

> We haven't had .wav files here for weeks.

They are still in the git repo because you didn't remove them from version control, so they still take the repo space.

I suggested to remove the files which you thought you deleted them but they are still there because Git is a version control system instead of a Cloud Drive.

The reasons:
- It violates GitHub's policy to store copyrighted content like a game ROM in Git version control.
- It makes the repo huge to store those files which you thought you removed from Git but they were still in the version control.

I didn't suggest to remove preview files which you didn't want to remove.

That's only my suggestion. I don't care whether it is accepted or not. I only clarify it to avoid any misunderstandings.

**Comment by Klokinator** [comment]
I already removed the rom. And the music preview files are staying... sort of the whole point of including them by splitting the music repo into its own thing.

**Comment by Klokinator** [comment]
Also considering you're working off some old build of this repo, you might want to update. We haven't had .wav files here for weeks.
